name: build-image-ya
on:
  push:
    paths:
      - "ya.Dockerfile"
      - "prepare-ya.sh"
    branches:
      - main

env:
  NAME: actions-runner
  REGISTRY: "cr.yandex/crpaerfcq9t16fse5onm"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-image:
    name: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "IMAGE=${{ env.REGISTRY }}/${{ env.NAME }}:${{ github.ref_name }}${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: build
        run: >-
          docker build
          --push
          -f ya.Dockerfile .
          --platform linux/amd64
          -t "${{ env.IMAGE }}" -t ${IMAGE%:*}:latest .
